# Generated by Django 3.1.1 on 2020-09-20 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('middlename', models.CharField(blank=True, max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SD', 'Student'), ('SG', 'Single'), ('MR', 'Married')], default='SG', max_length=2)),
                ('birthday', models.DateField(default=datetime.datetime(2020, 9, 20, 18, 14, 50, 334255))),
                ('contactNumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
