# Generated by Django 3.1.1 on 2020-09-20 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200920_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 9, 20, 18, 17, 30, 127449)),
        ),
    ]
