# Generated by Django 3.1.1 on 2020-09-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemId',
            field=models.ForeignKey(db_column='itemId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.item'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orderId',
            field=models.OneToOneField(db_column='orderId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(db_column='customerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer'),
        ),
    ]
