# Generated by Django 3.1.1 on 2020-09-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200921_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
