# Generated by Django 3.1.1 on 2020-10-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200924_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='_type',
            new_name='itemType',
        ),
    ]
