# Generated by Django 3.1.1 on 2020-10-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20201001_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orderId',
            field=models.OneToOneField(db_column='orderId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order'),
        ),
    ]
